language: python

os: linux
dist: focal

git:
  depth: 3
  quiet: true

python:
  #  - 3.5
  #  - 3.6
  #  - 3.7
  #  - 3.8
  - 3.9

before_install:
  - sudo apt-get update
  - sudo apt-get -y install bzip2 pbzip2 xz-utils wget zstd libzstd-dev # necessary for tests
  # on xenial (libzstd-dev 0.5.1) and bionic (libzstd-dev 1.3.3) libzstd-dev is too old for indexed_zstd
  - if [ "$TRAVIS_DIST" == xenial ] || [ "$TRAVIS_DIST" == bionic ]; then (
        cd -- $( mktemp -d ) &&
        wget -O- 'https://github.com/facebook/zstd/releases/download/v1.4.5/zstd-1.4.5.tar.gz' | tar -xzf- &&
        cd zstd*/ && sudo make install
    ); fi

install:
  # For some reason, the cffi dependency of lzmaffi is not installed at the correct time automatically
  - pip install --upgrade-strategy eager --upgrade cython twine pylint cffi

script:
  # test whether installation from tarball works
  - python3 setup.py sdist bdist_wheel
  - twine check dist/*
  - pip install "$( find dist -name '*.tar.gz' | head -1)"[full]
  # test ratarmount
  - bash tests/runtests.sh
  - ls -lart
  - ratarmount --help
  - ratarmount --version

env:
  global:
    # travis encrypt --com TWINE_PASSWORD=...
    - secure: "i2C7H6ffGaq67Xb/VnodOawXvGkOllCbXgXOWgdaHkX0ty4y93bZ4Fnpn2xx2DXIDXM48pAQQ/XPbozdyhlSH8qjn6zOJaz2Xxwqi76e05kBBmcUfBc/I5QulzybrfjPBQzIOADZaEl/1XxQgbp+NXmotpo9qRIIx2SNQsPC7g8PVebBnEZS+GUgsqLQmSVGPD4YJp/fOyVCYRi4SnIt0B7qkIeFBJ1/ERyzGLhDmVXhTgISy1BUgXr5Xw7rtylIb6vRPa/8SxIS8gHS4kLe9Eds+XSXJEuJZRVSmtHT0KnExCKdiLYn3y1ym0Mb3GvzC33pzIZW2lSUPj4BoTgdZxX1cQ1rBJ+IvKXnWIHBKMN4rd/7CAAeZTxqk9G+oeM3cB050K/p22LjqXLOejuh9GrUFl2m4xGMMlIHTiwE6/XzrmNtcxIQ2pzGHkgFVyAfiyfCCELrKlzcboa9+iI++Ut2heh8Z5ylU0AXUNDd9YtyXCL0rpWNDRULrJ/1Z2io3zcqwx8IIqTRnRhDaDDsP7EizPynwYWno5uJVQktTZiiJFrtOHqLAF8Y1vF4qYGv10rHyWfBCDqbb2rwV5pMcZQ+KRpS544jlh/anld8l76NUddvw3QBABPQaZhMdjLVGsBznIe9ZSVchwli5bNry1CbDCmJZkdDrmro6F0WpZM="

stages:
  - name: test
  - name: deploy
    if: tag =~ /^v/

jobs:
  include:
    - name: build-tarball
      stage: deploy
      script:
        - python3 setup.py sdist bdist_wheel
        - twine check dist/*
        - twine upload --skip-existing -u __token__ dist/*
